<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'No photos' => 'Нет фотографий',
    'No photos uploded for the following hotels: {link}. Follow the links to upload.' => 'Для следующих отелей нет фотографий: {link}. Для добавления пройдите по ссылкам.',
    'No photos uploded for the following rooms: {link}. Follow the links to upload.' => 'Для следующих номеров нет фотографий: {link}. Для добавления пройдите по ссылкам.',
    'No rooms registered yet in the following hotels: {link}. Follow the links to add.' => 'Для следующих отелей нет номеров: {link}. Для добавления пройдите по ссылкам.',
    'Not all prices are specified for the next 30 days for the following rooms: {link}. Follow the links to set prices.' => 'Для следующих номеров на ближайшие 30 дней проставлены не все цены: {link}. Для простановки цен пройдите по ссылкам.',
    'Please, <a href="{link}">add hotel photos</a>.' => 'Для продолжения работы <a href="{link}">добавьте фотографии отеля</a>.',
    'Please, <a href="{link}">add room photos</a>.' => 'Для продолжения работы <a href="{link}">добавьте фотографии номеров</a>.',
    'Please, <a href="{link}">add room prices</a>.' => 'Для возможности бронирования <a href="{link}">установите цены</a> на номер.',
    'Please, <a href="{link}">register rooms</a> to continue.' => 'Для продолжения работы <a href="{link}">зарегистрируйте номера</a> в отеле.',
    '<a href="{link}">Select the avaliable payment options</a> to activate on-site booking.' => 'Для подключения бронирования с сайта <a href="{link}">укажите допустимые способы оплаты</a>.',
    '<a href="{link}">Setup Yandex.Kassa</a> to activate online booking.' => 'Для подключения онлайн бронирования <a href="{link}">настройте Яндекс.Кассу</a>.',
    'Booking is limited' => 'Бронирование ограничено',
    'Booking is not available' => 'Бронирование недоступно',
    'Hotel registration is not complete' => 'Регистрация отеля не завершена',
    'No registered hotels' => 'Нет зарегистрированных отелей',
    'Please, <a href="{link}">register a hotel</a> to continue.' => 'Для продолжения работы <a href="{link}">зарегистрируйте отель</a>.',
    'Room registration is not complete' => 'Регистрация номера не завершена',
];
