<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add value' => 'Добавить значение',
    'Enter item value' => 'Введите значение элемента',
    'Lookup Field ID' => '',
    'Lookup Fields' => '',
    'Values' => 'Значения',
    'Are you sure you want to delete this item?' => 'Вы действительно хотите удалить эту запись?',
    'Create' => 'Добавить',
    'Create {modelClass}' => 'Добавить {modelClass}',
    'Delete' => 'Удалить',
    'ID' => 'ID',
    'Name' => 'Имя',
    'Reset' => 'Сброс',
    'Search' => 'Поиск',
    'Update' => 'Изменить',
    'Update {modelClass}: ' => 'Изменить {modelClass}:',
    'Users' => 'Пользователи',
    'Value En' => 'Значение En',
    'Value Ru' => 'Значение Ru',
];
