<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Contact person' => 'Контактное лицо',
    'Contact e-mail' => 'Контактный e-mail',
    'Domain' => 'Домен',
    'Notes' => 'Примечания',
    'Send request' => 'Отправить заявку',
    'Hotel domain request "{name}"' => 'Заявка на домен для отеля &laquo;{name}&raquo;',
    'Request for the hotel domain from {site}' => 'Заявка на домен с {site}',
    'Partner' => 'Партнер',
    'Hotel' => 'Отель',
    'Type the domain name you wish' => 'Напишите, какое доменное имя вам бы хотелось получить',
    'Domain registration request' => 'Заявка на регистрацию домена',
    'Domain exists already' => 'Домен уже зарегистрирован',
    'Check this if you already have the domain' => 'Отметьте, если домен уже зарегистрирован',
    'You are successfully applied for activation of "My domain" service' => 'Заявка на подключение услуги &laquo;Мой домен&raquo; успешно подана',
    '<p>Now your hotel Internet page of is located on the subdomain <i>{site}</i>. You can place it on your own domain in the domain zone <i>com</i>. To do this, fill out the form below. If you already have your personal domain, just fill out the domain name here. If you don&acute;t have domain, write here the preferred domain name and we will register it. In case this name is no more vacant, we will help you to choose a different name.</p> <p><span class="text-red">Attention!</span> By submitting this application, you automatically activate "My Domain" the service for 199 <i class="fa fa-rub"></i> monthly.</p>' => '<p>Сейчас интернет страница вашего отеля находится на поддомене <i>{site}</i>. Вы можете разместить ее на собственном домене в доменной зоне <i>ru</i>. Для этого заполните форму ниже. Если у вас уже есть домен, просто впишите его имя. Если домена нет, введите желаемое доменное имя, и мы его зарегистрируем. Если выбранное вами имя уже занято, мы поможем вам подобрать другое подходящее имя.</p><p><span class="text-red">Внимание!</span> Отправляя эту заявку, вы автоматически подключаете услугу &laquo;Мой домен&raquo; стоимостью 199 <i class="fa fa-rub"></i> в месяц.</p>',
];
