<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Age' => '@@Возраст@@',
    'Enter name' => '@@Введите имя@@',
    'Enter surname' => '@@Введите фамилию@@',
    'Gender' => '@@Пол@@',
    'Guests information' => '@@Информация о гостях@@',
    '{n, plural, =1{one guest} other{# guests}}' => '@@{n, plural, =1{один гость} one{# гость} few{# гостя} many{# гостей} other{# гостей}}@@',
    '{n, plural, =1{one night} few{# nights} many{# nights} other{# nights}}' => '@@{n, plural, =1{одна ночь} one{# ночь} few{# ночи} many{# ночей} other{# ночей}}@@',
    '* If you have' => '* Если имеется',
    'Adults' => 'Взрослых',
    'Arrival date' => 'Дата заезда',
    'Body' => 'Текст',
    'Booking' => 'Забронировать',
    'Children' => 'Детей 7-12 лет',
    'Contact information' => 'Контактная информация',
    'Contact us' => 'Обратная связь',
    'Departure date' => 'Дата выезда',
    'E-mail' => 'E-mail',
    'Email' => 'Email',
    'Enter your email. <br/>This email will be used to contact you and confirm booking.' => 'Введите ваш адрес электронной почты. <br/>Этот адрес будет использован для связи с Вами и для подтверждения заказа.',
    'Find' => 'Поиск',
    'Go to payment' => 'Перейти к оплате',
    'Guest name' => 'Имя гостя',
    'Guest surname' => 'Фамилия гостя',
    'Guests: {n}' => 'Гостей: {n}',
    'I want to pay {p}% ({s}) now and the rest at check-in.' => 'Я хочу заплатить {p}% ({s}) сейчас, а оставшуюся часть при заселении',
    'If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.' => 'Если у вас есть деловое предложение или другие вопросы, пожалуйста, заполните следующую форму, чтобы связаться с нами. Спасибо.',
    'Kids' => 'Дети 0-6 лет',
    'Main' => 'Главная',
    'Name' => 'Имя',
    'Nights: {n}' => 'Ночей: {n}',
    'Order information' => 'Информация о заказе',
    'Order number: <br/><code style="font-size:13px;">{n}</code>' => 'Номер заказа: <br/><code style="font-size:13px;">{n}</code>',
    'Order payment' => 'Оплата заказа',
    'Orders and payment management system for your hotels' => 'Система управления заказами и оплатой за заказы для вашего отеля.',
    'Page was not found!' => 'Страница не найдена!',
    'Pay' => 'Оплатить',
    'Pay options' => 'Варианты оплаты',
    'Phone number' => 'Номер телефона',
    'Promo code' => 'Промо код',
    'Room booking' => 'Бронирование номера',
    'Search' => 'Искать',
    'Subject' => 'Тема',
    'Submit' => 'Отправить',
    'Sum to pay now:' => 'Сумма для оплаты сейчас',
    'Surname' => 'Фамилия',
    'Thank you for contacting us. We will respond to you as soon as possible.' => 'Спасибо за сообщение! Мы обязательно Вам ответим!',
    'The rooms that you chose were booked. <br/><br/>To complete the booking you need to pay.<br/><br/>Otherwise, booking will be canceled within {t} hours.' => 'Выбранные Вами номера забронированны. <br/><br/>Для завершения процедуры бронирования необходимо произвести оплату.<br/><br/>В противном случае через {t} часа бронь аннулируется.',
    'There was an error sending email.' => 'Произошла ошибка при отправке электронного письма.',
    'Total sum:' => 'Общая сумма:',
    'Verification Code' => 'Проверочный код',
    '{n, plural, =1{photo} other{# photos}}' => '{n, plural, =1{фото} other{# фото}}',
];
