<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Adults' => 'Взрослых',
    'Age' => 'Возраст',
    'Arrival date' => 'Дата заезда',
    'Booking' => 'Дата выезда',
    'Children' => 'Детей 7-12 лет',
    'Contact information' => 'Контактная информация',
    'Departure date' => 'Дата выезда',
    'E-mail' => 'E-mail',
    'Enter name' => 'Введите имя',
    'Enter surname' => 'Введите фамилию',
    'Find' => 'Поиск',
    'Gender' => 'Пол',
    'Guests information' => 'Информация о гостях',
    'Kids' => 'Дети 0-7 лет',
    'Name' => 'Имя',
    'Order' => 'Заказ',
    'Order information' => 'Информация о заказе',
    'Phone number' => 'Номер телефона',
    'Search' => 'Искать',
    'Surname' => 'Фамилия',
    'female' => 'жен.',
    'male' => 'муж.',
];
