<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'I want to pay via bank transfer' => 'Я хочу оплатить банковским переводом',
    'Booking is completed' => 'Бронирование завершено',
    '<b>Rooms not found.</b> Please check information in form above' => '@@<b>Номера не найдены.</b> Пожалуйста, проверьте информацию в форме выше@@',
    'Go to payment' => '@@Перейти к оплате@@',
    'Thank you for your payment!' => '@@@@',
    '* If you have' => '* Если имеется',
    '<b>No rooms available for this period.</b> Please, select other days.' => '<b>На указанные даты свободные номера отсутствуют.</b> Пожалуйста, попробуйте другие даты',
    'Adults' => 'Взрослых',
    'Arrival date' => 'Дата заезда',
    'Body' => 'Текст',
    'Booking' => 'Забронировать',
    'Booking is not availible!' => 'Бронирование не возможно!',
    'Children' => 'Детей 7-12 лет',
    'Contact information' => 'Контактная информация',
    'Contact us' => 'Обратная связь',
    'Departure date' => 'Дата выезда',
    'E-mail' => 'E-mail',
    'Email' => 'Email',
    'Enter your email. <br/>This email will be used to contact you and confirm booking.' => 'Введите ваш адрес электронной почты. <br/>Этот адрес будет использован для связи с Вами и для подтверждения заказа.',
    'Find' => 'Поиск',
    'Guest name' => 'Имя гостя',
    'Guest surname' => 'Фамилия гостя',
    'Guests: {n}' => 'Гостей: {n}',
    'I want to make full payment at check in' => 'Я хочу оплатить всю сумму при заселении',
    'I want to pay {p}% ({s}) now and the rest at check-in.' => 'Я хочу заплатить {p}% ({s}) сейчас, а оставшуюся часть при заселении',
    'If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.' => 'Если у вас есть деловое предложение или другие вопросы, пожалуйста, заполните следующую форму, чтобы связаться с нами. Спасибо.',
    'Kids' => 'Дети 0-6 лет',
    'Main' => 'Главная',
    'Name' => 'Имя',
    'Next' => 'Далее',
    'Nights: {n}' => 'Ночей: {n}',
    'Order information' => 'Информация о заказе',
    'Order number: <br/><code style="font-size:13px;">{n}</code>' => 'Номер заказа: <br/><code style="font-size:13px;">{n}</code>',
    'Order number: <code>{n}</code>' => 'Номер заказа: <code>{n}</code>',
    'Order payment' => 'Оплата заказа',
    'Orders and payment management system for your hotels' => 'Система управления заказами и оплатой за заказы для вашего отеля.',
    'Page was not found!' => 'Страница не найдена!',
    'Pay' => 'Оплатить',
    'Pay options via Yandex.Money' => 'Варианты оплаты через Яндекс.Кассу',
    'Phone number' => 'Номер телефона',
    'Promo code' => 'Промо код',
    'Room booking' => 'Бронирование номера',
    'Search' => 'Искать',
    'Subject' => 'Тема',
    'Submit' => 'Отправить',
    'Sum to pay now:' => 'Сумма для оплаты сейчас',
    'Surname' => 'Фамилия',
    'Thank you for contacting us. We will respond to you as soon as possible.' => 'Спасибо за сообщение! Мы обязательно Вам ответим!',
    'The error occurred during the payment process!' => 'При выполнении оплаты произошла ошибка!',
    'The rooms that you chose were booked. <br/><br/>To complete the booking you need to pay.<br/><br/>Otherwise, booking will be canceled within {t} hours.' => 'Выбранные Вами номера забронированны. <br/><br/>Для завершения процедуры бронирования необходимо произвести оплату.<br/><br/>В противном случае через {t} часа бронь аннулируется.',
    'There was an error sending email.' => 'Произошла ошибка при отправке электронного письма.',
    'Total sum:' => 'Общая сумма:',
    'Try again' => 'Попробовать снова',
    'Try again later, by choosing a different payment method' => 'Попробуйте снова позже, выбрав иной способ оплаты',
    'Verification Code' => 'Проверочный код',
    'You have successfully completed the booking procedure.' => 'Вы успешно завершили процедуру бронирования.',
    'Your order #{n} has been paid.' => 'Ваш заказ №{n} был оплачен.',
    '{n, plural, =1{photo} other{# photos}}' => '{n, plural, =1{фото} other{# фото}}',
];
