<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Allow partial pay' => 'Позволить частичную оплату',
    'Are you sure you want to delete this item?' => 'Вы действительно хотите удалить этот элемент?',
    'Create' => 'Создать',
    'Create {modelClass}' => 'Создать {modelClass}',
    'Description En' => 'Описание En',
    'Description Ru' => 'Описание Ru',
    'Group ID' => 'ID группы',
    'Hotel ID' => 'ID отеля',
    'Image' => 'Изображение',
    'Important' => 'Важное',
    'Name En' => 'Имя En',
    'Name Ru' => 'Имя Ru',
    'Order' => 'Заказ',
    'Payment types' => 'Типы оплаты',
    'Percents to pay' => 'Проценты оплаты',
    'Reset' => 'Сброс',
    'Search' => 'Поиск',
    'Title En' => 'Название En',
    'Title Ru' => 'Название Ru',
    'View' => 'Просмотр',
    'Geo coordinates' => '@@Координаты@@',
    'Other information' => '@@Прочая информация@@',
    'Update' => '@@Редактировать@@',
    'Update {modelClass}: ' => '@@@@',
    'Address' => 'Адрес',
    'Category' => 'Категория',
    'Common information' => 'Общая информация',
    'Currency' => 'Валюта',
    'Delete' => 'Удалить',
    'Description' => 'Описание',
    'Edit' => 'Редактировать',
    'Facilities' => 'Особенности отеля',
    'Hotels' => 'Отели',
    'ID' => 'ID',
    'Images' => 'Фотографии',
    'Lat' => 'Широта',
    'Lng' => 'Долгота',
    'Name' => 'Название',
    'Partner ID' => 'ID партнера',
    'Rooms' => 'Номера',
    'Save' => 'Сохранить',
    'Timezone' => 'Временная зона',
    'Title' => 'Название',
];
