<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Address' => '@@Адрес@@',
    'Allow partial pay' => '@@Позволить частичную оплату@@',
    'Create {modelClass}' => '@@Создать {modelClass}@@',
    'Description' => '@@Описание@@',
    'Domain' => '@@Домен@@',
    'Title' => '@@Название@@',
    'Add hotel photos' => 'Добавьте фотографии отеля',
    'Allow partial advance payment' => 'Разрешить частичную предоплату',
    'Are you sure you want to delete this item?' => 'Вы действительно хотите удалить этот элемент?',
    'Category' => 'Категория',
    'Change your hotel page styles as you like' => 'Изменяйте стили страницы вашего отеля по своему вкусу',
    'Common information' => 'Общая информация',
    'Contact email' => 'Контактный Email',
    'Contact phone' => 'Контактный телефон',
    'Create' => 'Создать',
    'Create and enter the address of your hotel in system king.boo.com. Ex. palm-beach-hotel.' => 'Придумайте и введите адрес вашего отеля в системе king.boo.com. Например, palm-beach-hotel.',
    'Currency' => 'Валюта',
    'Custom CSS' => 'Стили CSS',
    'Delete' => 'Удалить',
    'Description En' => 'Описание En',
    'Description Ru' => 'Описание Ru',
    'Domain name of your hotel' => 'Домен вашего отеля',
    'Edit' => 'Редактировать',
    'Facilities' => 'Инфраструктура',
    'Fill in this field, if you want to register already existing personal domain of your hotel in king.boo system. If you still don’t have but want to register personal domain name for your hotel, please, apply for registration' => 'Поле требует заполнения, если вы хотите, чтоб в системе был зарегистрирован уже существующий персональный домен вашего отеля. Если домена еще нет, но вы хотите его зарегистрировать, пожалуйста, подайте заявку на регистрацию',
    'Frame on site' => 'Фрейм на сайт',
    'Group ID' => 'ID группы',
    'Hotel ID' => 'ID отеля',
    'Hotel address' => 'Адрес отеля',
    'Hotel description' => 'Описание отеля',
    'Hotel name' => 'Название отеля',
    'ID' => 'ID',
    'Image' => 'Изображение',
    'Images' => 'Фотографии',
    'Important' => 'Важное',
    'Information' => 'Информация',
    'Install on your site booking form' => 'Разместите на своем сайте форму поиска номеров и бронирования. Весь процесс бронирования будет происходить на вашем сайте.',
    'Install on your site widget for online booking' => 'Установите на свой сайт виджет для онлайн бронирования и оплаты',
    'Lat' => 'Широта',
    'Lng' => 'Долгота',
    'Manage photos' => 'Управление фотографиями',
    'Manage rooms' => 'Управление номерами',
    'My domain' => 'Мой домен',
    'Name En' => 'Имя En',
    'Name Ru' => 'Имя Ru',
    'No category' => 'Без категории',
    'No photos' => 'Нет фотографий',
    'Order' => 'Заказ',
    'Partner ID' => 'ID партнера',
    'Percents to pay' => 'Проценты оплаты',
    'Place your hotel web page on it&acute;s own domain name, not on <i>{site}</i> subdomain' => 'Разместить страницу отеля не на поддомене <i>{site}</i>, а на собственном доменном имени',
    'Register new hotel' => 'Зарегистрировать новый отель',
    'Reset' => 'Сброс',
    'Rooms' => 'Номера',
    'Save' => 'Сохранить',
    'Search' => 'Поиск',
    'Specify the minimum amount of partial advance payment' => 'Укажите минимальный размер предоплаты',
    'The currency in which prices for hotel rooms are shown.<br /><b class="text-red">Attention!</b><br />If you change hotel currency all room prices will be deleted!' => 'Валюта, в которой отображаются цены на номера отеля.<br /><b class="text-red">Внимание!</b><br />Если вы измените валюту отеля, все цены на его номера будут удалены!',
    'Timezone' => 'Временная зона',
    'Title En' => 'Название En',
    'Title Ru' => 'Название Ru',
    'URL' => 'URL',
    'View' => 'Просмотр',
];
