<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Allow partial pay' => '',
    'Are you sure you want to delete this item?' => '',
    'Create' => '',
    'Create {modelClass}' => '',
    'Description En' => '',
    'Description Ru' => '',
    'Group ID' => '',
    'Hotel ID' => '',
    'Image' => '',
    'Important' => '',
    'Name En' => '',
    'Name Ru' => '',
    'Order' => '',
    'Payment types' => '',
    'Percents to pay' => '',
    'Reset' => '',
    'Search' => '',
    'Title En' => '',
    'Title Ru' => '',
    'View' => '',
    'Geo coordinates' => '@@Координаты@@',
    'Other information' => '@@Прочая информация@@',
    'Update' => '@@Редактировать@@',
    'Update {modelClass}: ' => '@@@@',
    'Address' => 'Адрес',
    'Category' => 'Категория',
    'Common information' => 'Общая информация',
    'Currency' => 'Валюта',
    'Delete' => 'Удалить',
    'Description' => 'Описание',
    'Edit' => 'Редактировать',
    'Facilities' => 'Особенности отеля',
    'Hotels' => 'Отели',
    'ID' => 'ID',
    'Images' => 'Фотографии',
    'Lat' => 'Широта',
    'Lng' => 'Долгота',
    'Name' => 'Название',
    'Partner ID' => 'ID партнера',
    'Rooms' => 'Номера',
    'Save' => 'Сохранить',
    'Timezone' => 'Временная зона',
    'Title' => 'Название',
];
