<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Best regards, team of king-boo.com' => 'С наилучшими пожеланиями, команда king-boo.com',
    'Dear visitor!' => 'Дорогой посетитель',
    'You left registration request on partner.king-boo.com. To continue, please, follow the link below:' => 'Вы начали регистрацию на сайте partner.king-boo.com. Для продолжения, пожалуйста, перейдите по ссылке ниже:',
    'Please, use following data to login:' => 'Пожалуйста, для входа на сайт используйте следующие данные:',
    'email: {email}' => 'email: {email}',
    'password: {password}' => 'пароль: {password}',
];
