<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Best regards, team of king-boo.com' => 'Команда King-Boo.',
    'Dear visitor!' => 'Дорогой посетитель',
    'You left registration request on partner.king-boo.com. To continue, please, follow the link below:' => 'Вы начали регистрацию на сайте partner.king-boo.com. Для продолжения, пожалуйста, перейдите по ссылке ниже:',
    'Please, use following data to login:' => 'Для входа на сайт используйте следующие данные:',
    'E-mail' => 'e-mail',
    'password' => 'пароль',

    'Your personal manager' => 'Ваш персональный менеджер',
    'Svetlana' => 'Светлана',
    'You can communicate to her any time.' => 'Обращайтесь к ней по любым возникающим вопросам.',
    'Contact phone' => 'Контактный телефон',
    'Contact email' => 'Контактный e-mail',

    '<p>You can see all about King-Boo on <a href="{site}">website</a>.</p>' => '<p>Система King-Boo позволит вам:</p><ul>
<li>получить собственный профессиональный сайт отеля, если у вас его еще нет</li>
<li>подключить к сайту вашего отеля удобную и многофункциональную систему бронирования и онлайн-оплаты</li>
<li>воспользоваться встроенной системой IP телефонии для удобной связи клиентов с вашим отелем</li>
</ul>
<p>Подробнее о возможностях системы можно узнать на сайте <a href="{site}/about">www.king-boo.com</a></p>',

    'You can see all about King-Boo on website {site}.' => 'Система King-Boo позволит вам:
получить собственный профессиональный сайт отеля, если у вас его еще нет
подключить к сайту вашего отеля удобную и многофункциональную систему бронирования и онлайн-оплаты
воспользоваться встроенной системой IP телефонии для удобной связи клиентов с вашим отелем

Подробнее о возможностях системы можно узнать на сайте www.king-boo.com',
];
