<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'The rooms are booked now. On arrival you will need to pay the full cost of the order - {sum}.' => 'Номера забронированы. При заселении Вам необходимо будет выполнить',
    'Adults: <b>{n}</b>' => 'Взрослых: <b>{n}</b>',
    'Adults: {n}' => 'Взрослых: {n}',
    'Best regards, team of king-boo.com' => 'C уважением, команда king-boo.com',
    'Check-in date' => 'Дата заезда',
    'Check-out date' => 'Дата выезда',
    'Children 0-6 y.o.: <b>{n}</b>' => 'Детей 0-6 лет: <b>{n}</b>',
    'Children 0-6 y.o.: {n}' => 'Дети 0-6 лет: {n}',
    'Children 7-12 y.o.: <b>{n}</b>' => 'Детей 7-12 лет: <b>{n}</b>',
    'Children 7-12 y.o.: {n}' => 'Дети 7-12 лет: {n}',
    'Contact information' => 'Контактная информация',
    'Dear, {name}!' => 'Уважаемый(ая), {name}!',
    'Hello!' => 'Здравствуйте!',
    'Hello, {name}!' => 'Здравствуйте, {name}!',
    'Hotel' => 'Отель',
    'Hotel information' => 'Информация об отеле',
    'New order on site king-boo.com' => 'Новый заказ на сайте king-boo.com',
    'Nights: {n}' => 'Ночей: {n}',
    'Order #{n} has been made on site <a href="http://king-boo.com">king-boo.com</a>.' => 'Заказ №{n} был совершен на сайте <a href="http://king-boo.com">king-boo.com</a>.',
    'Order #{n} has been made on site king-boo.com.' => 'Заказ №{n} был совершен на сайте king-boo.com.',
    'Order details' => 'Детали заказа',
    'Order number: {n}' => 'Номер заказа: {n}',
    'Order on site king-boo.com' => 'Заказ на сайте king-boo.com',
    'Order sum' => 'Сумма заказа',
    'Order\'s #{n} status was changed' => 'Статус заказа №{n} был изменён.',
    'Pay sum' => 'Сумма оплаты',
    'Rooms' => 'Номера',
    'Status' => 'Статус',
    'Status of order #{n} was changed to "{new_status}".' => 'Статус заказа №{n} был изменен на "{new_status}".',
    'Status of your order #{n} was changed to "{new_status}".' => 'Статус Вашего заказа №{n} был изменен на "{new_status}".',
    'Sum' => 'Сумма',
    'The rooms are now booked, but the booking will be canceled if payment is not received within 24 hours.' => 'Номера сейчас забронированы, но бронь будет аннулирована, если оплата не поступит в течение 24 часов.',
    'To make a payment, please click the link below <br/><a href="{url}">{url}</a>' => 'Для оплаты, пожалуйста, перейдите по ссылке ниже <br/><a href="{url}">{url}</a>',
    'To make a payment, please open the link below in your browser: 
{url}' => 'Для оплаты, пожалуйста, откройте ссылку в вашем браузере:
{url}',
    'You can open order to manage it by <a href="{url}">clicking here</a>.' => 'Вы можете перейти к управлению заказом <a href="{url}">нажав на ссылку</a>.',
    'You made a order on the site <a href="http://king-boo.com">king-boo.com</a>.' => 'Вы совершили заказ на сайте <a href="http://king-boo.com">king-boo.com</a>.',
    'Your order\'s #{n} status was changed' => 'Статус Вашего заказа №{n} был изменен.',
    'd/m/Y' => 'd.m.Y',
];
