<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Post Params' => '',
    'Room ID' => '',
    'Server Params' => '',
    'Timestamp' => '',
    'Updated At' => '',
    'Checked' => '@@@@',
    'Customer Number' => '@@Номер клиента@@',
    'Invoice ID' => '@@ID счета@@',
    'Order Created Datetime' => '@@Дата создания заказа@@',
    'Order Number' => '@@Номер заказа@@',
    'Order Sum Amount' => '@@Сумма заказа@@',
    'Order Sum Bank Paycash' => '@@@@',
    'Order Sum Currency Paycash' => '@@@@',
    'Payed' => '@@Сумма оплаты@@',
    'Payment Datetime' => '@@@@',
    'Payment Payer Code' => '@@@@',
    'Payment Type' => '@@@@',
    'Shop Sum Amount' => '@@@@',
    'Shop Sum Bank Paycash' => '@@@@',
    'Shop Sum Currency Paycash' => '@@@@',
    'Address' => 'Обращение',
    'Adults' => 'Взрослых',
    'Allow full payment at checkin' => 'Разрешить оплату при заселении',
    'Allow payment via bank transfer' => 'Разрешить оплату банковским переводом',
    'Children' => 'Дети 7-12 лет',
    'Created At' => 'Дата создания',
    'Date From' => 'Дата заезда',
    'Date To' => 'Дата выезда',
    'Email' => 'Email',
    'ID' => 'ID',
    'Kids' => 'Дети 0-6 лет',
    'Name' => 'Имя',
    'Number' => 'Номер',
    'Order ID' => 'ID заказа',
    'Partial Pay' => 'Частичная оплата',
    'Partial Pay Percent' => 'Процент частичной оплаты',
    'Pay Sum' => 'Сумма для оплаты',
    'Phone' => 'Тел. номер',
    'Promo code' => 'Промо код',
    'Status' => 'Статус',
    'Sum' => 'Сумма',
    'Surname' => 'Фамилия',
    'cancelled' => 'аннулирован',
    'checkin full pay' => 'полная оплата при заезде',
    'payed' => 'оплачен',
    'waiting for pay' => 'ожидает оплаты',
];
