<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => 'Вы действительно хотите удалить этот элемент?',
    'Comment' => 'Комментарий',
    'Common information' => 'Общая информация',
    'Compiled Css' => 'Скомпилированный Css',
    'Compiled Js' => 'Скомпилированный Js',
    'Copy this code and insert in the place where widget should be located.' => 'Скопируйте этот код и вставьте в то место, где виджет должен должен быть расположен',
    'Create' => 'Создать',
    'Create Widget' => 'Создать виджет',
    'Delete' => 'Удалить',
    'Hash Code' => 'HASH код',
    'Hotel ID' => 'Отель',
    'ID' => '',
    'No' => 'Нет',
    'Options' => 'Параметры',
    'Params' => '',
    'Reset' => 'Сбросить',
    'Search' => 'Поиск',
    'Update' => 'Обновить',
    'Update {modelClass}: ' => '',
    'Widget id:' => '',
    'Widgets' => 'Виджеты',
    'Yes' => 'Да',
    'Widgets are absent' => 'Виджеты отсутствуют',
    'Press upper button to create new widget.' => 'Нажмите кнопку выше для создания нового виджета.',
];
