<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'ID' => '',
    'Params' => '',
    'Widget id:' => '',
    'Are you sure you want to delete this item?' => 'Вы действительно хотите удалить этот элемент?',
    'Back to widgets' => 'Вернуться к виджетам',
    'Comment' => 'Комментарий',
    'Common information' => 'Общая информация',
    'Compiled Css' => 'Скомпилированный Css',
    'Compiled Js' => 'Скомпилированный Js',
    'Copy this code and insert in the place where widget should be located.' => 'Скопируйте этот код и вставьте в то место, где виджет должен должен быть расположен',
    'Create' => 'Создать',
    'Create Widget' => 'Создать виджет',
    'Delete' => 'Удалить',
    'Hash Code' => 'HASH код',
    'Hotel ID' => 'Отель',
    'No' => 'Нет',
    'Options' => 'Параметры',
    'Press upper button to create new widget.' => 'Нажмите кнопку выше для создания нового виджета.',
    'Update' => 'Обновить',
    'Widget #{n} edit' => 'Редактирование виджета №{n}',
    'Widgets' => 'Виджеты',
    'Widgets are absent' => 'Виджеты отсутствуют',
    'Yes' => 'Да',
    '<p>If you already have personal website of your hotel (not in the <i>{site}</i>), you can install widget for online booking and payment on it. When widget installation is suggessfully complete, a special code is generated. All you need is to insert this code into HTML code of your site to the place where you want to locate the widget, and online payment system is ready to use!</p>' => '<p>Если у вашего отеля есть собственный сайт (не в системе <i>{site}</i>), вы можете установить на него виджет для онлайн бронирования и оплаты. После установки виджета генерируется код, который достаточно вставить в HTML код сайта в то место, где вы хотите видеть виджет, и полноценная система оплаты готова к использованию!</p>',
];
