<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Back to all messages' => 'Назад ко всем сообщениям',
    'Dialog #{n}' => 'Диалог №{n}',
    'Message {n}' => 'Сообщение №{n}',
    'New message' => 'Новое сообщение',
    'Start new dialog' => 'Начать новый диалог',
    'Support messages' => 'Сообщения службы поддержки',
    'd/m/Y' => 'd.m.Y',
    'd/m/Y H:i:s' => 'd.m.Y H:i:s',
    'Support' => 'Поддержка',
    'Dialogs are absent' => 'Диалоги отсутствуют',
    'Press upper button to start dialog.' => 'Нажмите на кнопку выше для начала общения.',
    'Back to list of messages' => 'Вернуться к списку сообщений',
    'Submit a request' => 'Задать вопрос в службу поддержки',
];
