<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<b>Yandex.Money is not configured.</b><br>Your customers can not make online payments.<br>For integration with Yandex.Money, please, enter the required settings on the <a href="/profile">Profile page</a>.' => '<b>Яндекс.Касса не настроена.</b><br>Ваши клиенты не смогут оплатить заказы онлайн.<br>Для интеграции с Яндекс.Кассой введите необходимые параметры на странице <a href="/profile">Профиля</a>',
    '<b>Your clients can not make reservation!</b><br>The full payment at check in option is not activated, and  integration with Yandex.Money is not configured.' => '<b>Ваши клиенты не могут выполнять бронирование!</b><br>Отключена возможность полной оплаты при заселении, возможность оплаты банковским переводом, а так же не настроена интеграция с Яндекс.Кассой.<br>Включить необходимые опции можно в <a href="/profile">Профиле</a>',
    'dd/mm/yyyy' => 'dd.mm.yyyy',
];
