<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Yandex Kassa' => 'Яндекс Касса',
    'Apply' => 'Применить',
    'Cancel' => 'Отмена',
    'Cell phone number' => 'Номер мобильного телефона',
    'Configuration of IP telephony' => 'Настройка IP телефонии',
    'Enable full payment at check in option' => 'Включить возможность полной оплаты при заселении',
    'Enable payment via bank transfer' => 'Включить возможность оплаты через банковский перевод',
    'Extra charge to the official exchange rate, %' => 'Надбавка к официальному курсу валют в %',
    'If you use the online payment system, this percentage will be added to the official exchange rate at conversion from one currency into another. For example, official rate + 2%.' => 'Если вы используете систему онлайн оплаты, при конвертации из одной валюты в другую этот процент будет добавляться к официальному курсу. Например, курс ЦБ + 2%.',
    'Name of the legal person' => 'Название юр. лица.',
    'Password' => 'Пароль',
    'Password change' => 'Смена пароля',
    'Payment details' => 'Платежные реквизиты',
    'Payment methods' => 'Способы оплаты',
    'Payment options' => 'Варианты оплаты',
    'Profile' => 'Профиль',
    'Profile settings' => 'Настройки профиля',
    'Profile successfully saved' => 'Профиль успешно сохранён',
    'Setting of these parameters will allow your customers to make calls directly from the website.' => 'Установка этих параметров позволит Вашим клиентам совершать звонки прямо с сайта.',
    'Shop identifier (shopId)' => 'Идентификатор магазина (shopId)',
    'Shop password (shopPassword)' => 'Пароль магазина (shopPassword)',
    'Showcase identifier (scid)' => 'Идентификатор витрины (scid)',
    'Yandex.Money payment setup' => 'Настройка оплаты через Яндекс.Деньги',
    'Demo mode' => 'Тестовый режим',
];
