<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'You should enable at least one condition to apply discount.' => 'Необходимо указать хотя бы одно условие действия скидки.',
    'Booking date range' => 'Диапазон даты бронирования',
    'Code' => 'Код',
    'Dates in booking date range should be defined.' => 'Даты диапазона даты бронирования должны быть заданы.',
    'Dates in living date range should be defined.' => 'Даты дианазона дат проживания должны быть заданы.',
    'Discount code should be set. It should contain letters, digits and following chars: <code>!</code> <code>+</code> <code>-</code> <code>_</code>' => 'Код скидки должет быть задан. Он должен содержать буквы, цифры и следующие символы: <code>!</code> <code>+</code> <code>-</code> <code>_</code>',
    'Living dates range' => 'Диапазон дат проживания',
    'Maximum discount bound' => 'Максимальный порог скидки',
    'Minimum discount bound' => 'Минимальный порог скидки',
    'Select condition' => 'Выбрать условие',
    'Select rooms' => 'Выбрать номера',
    'Start date range must be before the end date.' => 'Дата начала диапазона должна быть раньше даты окончания.',
    'Value of discount is incorrect' => 'Неверное значение скидки',
    'Value of discount should be set and be greater than 0.' => 'Значение скидки должно быть задано, а так же должно быть больше 0.',
    'Value of maximal sum discount bound should be set and be greater than 0.' => 'Значение максимальной границы скидки.',
    'Value of minimal sum discount bound should be set and be greater than 0.' => 'Значение минимальной границы скидки.',
    'You should select at least one room to apply discount.' => 'Необходимо выбрать хотя бы одну комнату для применения скидки.',
];
