<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Copy this code and paste it into the corresponding place on your page:' => 'Скопируйте этот код и вставьте его в необходимое место на странице:',
    'Domain' => 'Домен',
    'Frame code' => 'Код фрейма',
    'Frame on your site' => 'Фрейм на Ваш сайт',
    'Frame preview' => 'Предпросмотр фрейма',
    'Height (px)' => 'Высота (пикс.)',
    'Hide description and photos' => 'Спрятать описание и фото',
    'Set width 100%' => 'Установить ширину в 100%',
    'You can place search form with hotel description on your site or page using <code>iframe</code> tag.' => 'Вы можете поместить форму поиска и описание отеля на свой сайт используя форму <code>iframe</code> тэг.',
];
