<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Enable full payment at check in option' => 'Включить возможность полной оплаты при заселении',
    'Enable payment via bank transfer' => 'Включить возможность оплаты через банковский перевод',
    'Payment options' => 'Варианты оплаты',
    'Yandex.Money payment setup' => 'Настройка оплаты через Яндекс.Деньги',
    'Yandex Kassa' => '@@Яндекс Касса@@',
    'Apply' => 'Применить',
    'Cancel' => 'Отмена',
    'Password change' => 'Смена пароля',
    'Payment methods' => 'Способы оплаты',
    'Profile' => 'Профиль',
    'Profile settings' => 'Настройки профиля',
    'Profile successfully saved' => 'Профиль успешно сохранён',
    'Shop identifier (shopId)' => 'Идентификатор магазина (shopId)',
    'Shop password (shopPassword)' => 'Пароль магазина (shopPassword)',
    'Showcase identifier (scid)' => 'Идентификатор витрины (scid)',
];
