<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add hotel' => 'Добавить отель',
    'Adminstrative panel' => 'Администранивная панель',
    'Hotels' => 'Отели',
    'New' => 'Новый',
    'Nights: {n}' => 'Ночей: {n}',
    'Order #{n}' => 'Заказ №{n}',
    'Orders' => 'Заказы',
    'Support messages' => 'Сообщения службы поддержки',
    'View all orders' => 'Все заказы',
    'View all support messages' => 'Все сообщения',
    'd/m/Y' => 'd.m.Y',
    'd/m/Y H:i:s' => 'd.m.Y H:i:s',
    '{n, plural, =1{# new message} other{# new messages}}' => 'Новых сообщений: {n}',
    '{n, plural, =1{# new order} other{# new orders}}' => 'Новых заказов: {n}',
];
