<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to cancel this order?' => 'Вы действительно хотите аннулировать тот заказ?',
    'Cancel order' => 'Отменить заказ',
    'Set as payed' => 'Отметить как оплачен',
    'bank transfer' => 'банковский перевод',
    '(partial pay {percents}%)' => '(частичная оплата {percents}%)',
    'Adults' => 'Взрослые',
    'Adults: {n}' => 'Взрослых: {n}',
    'Back to all orders' => 'Вернуться к заказам',
    'Cancelled' => 'Отменён',
    'Children' => 'Дети 7-12 лет',
    'Children: {n}' => 'Детей 7-12 лет: {n}',
    'Contact info' => 'Контактная информация',
    'Contact information' => 'Контактная информация',
    'Create time' => 'Время создания',
    'Date' => 'Дата',
    'Dates range' => 'Диапазон дат',
    'Email' => 'Email',
    'Full pay at check in' => 'Полная оплата при заселении',
    'H:i:s' => 'H:i:s',
    'Hotel' => 'Отель',
    'Kids' => 'Дети 0-6',
    'Kids: {n}' => 'Детей 0-6: {n}',
    'Nights' => 'Ночей',
    'No orders have been made yet.' => 'Пока никто ничего не заказывал',
    'Number' => 'Номер',
    'Order #{n}' => 'Заказ №{n}',
    'Order sum' => 'Сумма заказа',
    'Orders' => 'Заказы',
    'Orders are absent' => 'Заказы отсутствуют',
    'Orders list' => 'Список заказов',
    'Pay status' => 'Статус оплаты',
    'Pay sum' => 'Сумма оплаты',
    'Payed' => 'Оплачен',
    'Phone' => 'Телефон',
    'Please add some photos to hotel.' => 'Добавьте, пожалуйста, фотографии для отеля.',
    'Print' => 'Печать',
    'Room and guest' => 'Комната и гость',
    'Rooms' => 'Комнаты',
    'Set as viewed' => 'Отметить как просмотренный',
    'Status' => 'Статус',
    'Sum' => 'Сумма',
    'Waiting payment' => 'Ожидание оплыты',
    'd/m/Y' => 'd.m.Y',
    'd/m/Y H:i:s' => 'd.m.Y H:i:s',
];
