<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add discount' => 'Добавить скидку',
    'Add price rules using buttons above.' => 'Добавьте правила формирования цен используя кнопки выше',
    'Additive' => 'Аддитивная',
    'Are you sure you want to deactivate this price rule?' => 'Вы действительно хотите деактивировать это правило?',
    'Back to price rules' => 'Вернуться к правилам форм. цен',
    'Booking date range' => 'Диапазон даты бронирования',
    'Booking dates range' => 'Диапазон даты бронирования',
    'Check code' => 'Проверить код',
    'Check-in date range' => 'Диапазон даты заселения',
    'Correct errors' => 'Исправить ошибки',
    'Create' => 'Создать',
    'Create {price_rule}' => 'Создать {price_rule}',
    'Discount value' => 'Значение скидки',
    'Discounts' => 'Скидки',
    'Errors in form!' => 'В форме имеются ошибки',
    'Fixed sum. Currency depends from hotel\'s currency.' => 'Фиксированная сумма. Валюта зависит от установленной валюты отеля.',
    'Living date range' => 'Диапазон на срок бронирования',
    'Living dates range' => 'Диапазон дат проживания',
    'Maximal discount sum limit' => 'Ограничение максимальной суммы скидки',
    'Maximum discount bound' => 'Ограничение максимальной суммы',
    'Minimal discount sum limit' => 'Ограничение минимальной суммы скидки',
    'Minimum discount bound' => 'Ограничение минимальной суммы',
    'Options' => 'Параметры',
    'Price rules' => 'Правила формирования цен',
    'Price rules not defined' => 'Правила формирования цен не определены',
    'Promo code' => 'Промо код',
    'Rooms' => 'Номера',
    'Status' => 'Статус',
    'Type' => 'Тип',
    'active' => 'активно',
    'd/m/Y' => 'd.m.Y',
    'deactivate' => 'деактивировать',
    'inactive' => 'не активно',
    'percents' => 'проценты',
    'sum' => 'сумма',
    'to' => 'по',
    'No discounts have been created yet' => 'Скидки еще не созданы',
    'Use the button above to create a new discount.' => 'Для добавления скидки используйте кнопку выше.',
    'Type of the discount' => 'Тип скидки',
    'Size of the discount' => 'Величина скидки',
    'Early booking discount' => 'Скидка для раннего бронирования',
    'Promotional code discount' => 'Скидка по промокоду',
    'Discount for reservation period' => 'Скидка на даты проживания',
    'Set the minimum discount' => 'Ограничение по минимальному размеру скидки',
    'Set the maximum discount' => 'Ограничение по максимальному размеру скидки',
    'promo action' => 'промоакция',
    'Dates' => 'Даты',
    'Back to discount list' => 'Вернуться к списку скидок',
];
