<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Additive' => 'Аддитивная',
    'Are you sure you want to deactivate this price rule?' => 'Вы действительно хотите деактивировать это правило?',
    'Booking dates range' => 'Диапазон даты бронирования',
    'Check-in date range' => 'Диапазон даты заселения',
    'Living dates range' => 'Диапазон дат проживания',
    'Maximal discount sum limit' => 'Ограничение максимальной суммы скидки',
    'Minimal discount sum limit' => 'Ограничение минимальной суммы скидки',
    'Nothing was found' => 'Ничего не найдено',
    'Promo code' => 'Промо код',
    'Status' => 'Статус',
    'Type' => 'Тип',
    'active' => 'активно',
    'd/m/Y' => 'd.m.Y',
    'deactivate' => 'деактивировать',
    'inactive' => 'не активно',
    'Add price rule' => 'Добавить правило',
    'Booking date range' => 'Диапазон даты бронирования',
    'Check code' => 'Проверить код',
    'Correct errors' => 'Исправить ошибки',
    'Create' => 'Создать',
    'Create {price_rule}' => 'Создать {price_rule}',
    'Discount value' => 'Значение скидки',
    'Errors in form!' => 'В форме имеются ошибки',
    'Fixed sum. Currency depends from hotel\'s currency.' => 'Фиксированная сумма. Валюта зависит от установленной валюты отеля.',
    'Living date range' => 'Диапазон на срок бронирования',
    'Maximum discount bound' => 'Ограничение максимальной суммы',
    'Minimum discount bound' => 'Ограничение минимальной суммы',
    'Options' => 'Параметры',
    'Price rules' => 'Правила формирования цен',
    'Rooms' => 'Номера',
    'percents' => 'проценты',
    'sum' => 'сумма',
    'to' => 'по',
];
