<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Confirmation code was sent to your email. <br><a href="{url}" class="btn btn-link">Resend</a>' => 'На ваш email было выслано письмо с информацией о регистрации. Для продолжения работы подтвердите ваш e-mail, пройдя по ссылке в этом письме.<br><a href="{url}" class="btn btn-link">Выслать письмо еще раз.</a>',
    'User not found!' => 'Пользователь не найден!',
    'Confirmation code was sent to your email.' => 'Код подтверждения был выслан на Ваш email',
    'Email confirmation for site partner.king-boo.com' => 'Подтверждение email на сайте partner.king-boo.com',
    'I forgot my password' => 'Я забыл пароль',
    'Password reset for partner.king-boo.com' => 'Сброс пароля на сайте partner.king-boo.com',
    'Please fill out the following fields to sign up:' => 'Пожалуйста, заполните следующие поля для регистрации:',
    'Please fill out your email. A link to reset password will be sent there.' => 'Пожалуйста, введите свой е-mail, на него будет отправлена ссылка для создания нового пароля.',
    'Request password reset' => 'Запрос сброса пароля',
    'Send' => 'Отправить',
    'Sign In' => 'Вход',
    'Sign in' => 'Вход',
    'Sign in to start your session' => 'Выполните вход для работы с сервисом',
    'Sign up' => 'Регистрация',
    'Signup' => 'Зарегистрироваться',
    'There is no user with such email.' => 'Пользователя с таким адресом не найдено.',
    'This email address has already been taken.' => 'Этот адрес уже занят.',
    'User not found' => 'Пользователь не найден',
    'You shoould confirm email address to continue' => 'Для работы в системе необходимо подтвердить ваш e-mail. Для этого пройдите по ссылке в письме, высланном вам при регистрации.',
];
