<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Price rule deactivation is not allowed' => 'Отключение правило запрещено',
    'Price rule not found' => 'Правило не найдено',
    'Unknown error' => 'Неизвестная ошибка',
    'Additive' => 'Аддитивная',
    'Additive discount will be applyed all time. All additive discounts will be summarized and added to one maximal non-additive discount.' => 'Аддитивные скидки будут применены всегда. Все подходящие аддитивные скидки будут просуммированы и добавлены к одной максимальной обычной',
    'Apply range for check-in date' => 'Применить диапазон к дате заселения',
    'Booking date from' => 'Дата бронирования с',
    'Booking date to' => 'Дата бронирования по',
    'Check code for discount' => 'Проверочный код для скидки',
    'Commencement of discount' => 'Начало действия скидки',
    'Counter' => 'Счетчик',
    'Date from' => 'Дата с',
    'Date to' => 'Дата по',
    'Discount' => 'скидку',
    'Discount promo code' => 'Промо код скидки',
    'Discount value' => 'Величина скидки',
    'End booking date range' => 'Окончание диапазона даты бронирования',
    'Expiry date discount' => 'Окончание действия скидки',
    'ID' => 'ID',
    'If checked check-in date should be in living range. Will affect all days in range you booking' => 'Если отмечено, дата заезда должна быть в указаном диапазоне. Скидка будет применена на весь срок бронирования',
    'If discount of sum for single day will be less than this sum it will be increased to this value' => 'Если сумма скидки будет меньше заданной, то скидка бодет увеличина до этого значения.',
    'If discount of sum for single day will be more than this sum it will be decreased to this value' => 'Если сумма скидки будет больше заданной, то скидка бодет уменьшена до этого значения.',
    'Maximal sum of discount' => 'Максимальная сумма скидки',
    'Minimal sum of discount' => 'Минимальная сумма скидки',
    'Params' => 'Параметры',
    'Price rule' => 'Правило формирования цены',
    'Start booking date range' => 'Начало диапазона даты бронирования',
    'Type' => 'Тип',
    'Type of discount' => 'Тип скидки',
    'Type of value' => 'Тип значения',
    'Type of value (% or fixed sum)' => 'Тип значения (% или фиксированная сумма)',
    'Value' => 'Занчение',
    'active' => 'активно',
];
