<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Price rule deactivation is not allowed' => 'Отключение правило запрещено',
    'Price rule not found' => 'Правило не найдено',
    'Unknown error' => 'Неизвестная ошибка',
    'Additive' => 'Аддитивная',
    'Additive discount will be applyed all time. All additive discounts will be summarized and added to one maximal non-additive discount.' => 'Аддитивные скидки будут применены всегда. Все подходящие аддитивные скидки будут просуммированы и добавлены к одной максимальной обычной',
    'Apply range for check-in date' => 'Применить диапазон к дате заселения',
    'Booking date from' => 'Дата бронирования с',
    'Booking date to' => 'Дата бронирования по',
    'Check code for discount' => 'Проверочный код для скидки',
    'Commencement of discount' => 'Начало действия скидки',
    'Counter' => 'Счетчик',
    'Date from' => 'Дата с',
    'Date to' => 'Дата по',
    'Discount' => 'скидку',
    'Discount promo code' => 'Промо код скидки',
    'Discount value' => 'Величина скидки',
    'End booking date range' => 'Окончание диапазона даты бронирования',
    'Expiry date discount' => 'Окончание действия скидки',
    'ID' => 'ID',
    'If checked check-in date should be in living range. Will affect all days in range you booking' => 'Если отмечено, дата заезда должна быть в указаном диапазоне. Скидка будет применена на весь срок бронирования',
    'If discount of sum for single day will be less than this sum it will be increased to this value' => 'Если сумма скидки будет меньше заданной, то скидка бодет увеличина до этого значения.',
    'If discount of sum for single day will be more than this sum it will be decreased to this value' => 'Если сумма скидки будет больше заданной, то скидка бодет уменьшена до этого значения.',
    'Maximal sum of discount' => 'Максимальная сумма скидки',
    'Minimal sum of discount' => 'Минимальная сумма скидки',
    'Params' => 'Параметры',
    'Price rule' => 'Правило формирования цены',
    'Start booking date range' => 'Начало диапазона даты бронирования',
    'Type' => 'Тип',
    'Type of discount' => 'Тип скидки',
    'Type of value' => 'Тип значения',
    'Type of value (% or fixed sum)' => 'Тип значения (% или фиксированная сумма)',
    'Value' => 'Занчение',
    'active' => 'активно',
    'Size of the discount' => 'Размер скидки',
    'Promotional code' => 'Промокод',
    'Minimum discount' => 'Минимальная скидка',
    'Maximum discount' => 'Максимальная скидка',
    'Apply the discount for the whole booking period' => 'Применить скидку на весь период бронирования',
    'All additive discounts are summarized in one overall discount. If the option is unchecked, only the biggest non-additive discount for booking is applied.' => 'Все аддитивные скидки суммируются в одну общую скидку. При отключенной опции действует только максимальная из неаддитивных скидок на бронь.',
    'Discount in % is calculated as a percentage of the total package price. For promoaction a fixed amount is deducted from any reservation order.' => 'Если выбраны %, рассчитывается скидка в процентах от общей стоимости брони. Если выбрана промоакция, из суммы любого заказа вычитается фиксированная сумма.',
    'The period of the early booking discount validity (Attn: specify here the period when reservation should be made for early booking discount be valid, NOT the real stay in the hotel period!).' => 'Период действия скидки по раннему бронированию (Внимание: укажите период, когда должно быть оформлено раннее бронирование для действия скидки, а не даты проживания!).',
    'Discount for clients who enter the specified promotional code at reservation (eg. regular clients).' => 'Скидка предоставляется клиентам, которые при оформлении брони введут указанный промокод (например, постоянные клиенты).',
    'Tick is the discount is valid for all reservation  days if the arrival date falls under the marked period. Do not tick if the discount is valid only for reservation days falling under the specified period, regardless of the arrival date.' => 'Отметьте, чтоб применить скидку на весь период бронирования, если дата заезда попала в отмеченный диапазон. Не отмечайте, если скидка действует только для дат брони, попадающих в указанный период, независимо от даты заезда.',
    'If the discount calculated in Sec. 2 is smaller than the value given here, the size of the minimum discount will be increased to this value, and the total reservation sum will be recalculated automatically.' => 'Если рассчитанная в п. 2 величина скидки меньше заданной здесь, размер минимальной скидки увеличится до этого значения, а стоимость брони автоматически пересчитается.',
    'If the discount calculated in Sec. 2 is bigger than the value given here, the size of the maximum discount will be decreased to this value, and the total reservation sum will be recalculated automatically.' => 'Если рассчитанная в п. 2 сумма скидки выше заданной здесь, размер минимальной скидки уменьшится до этого значения, а стоимость брони автоматически пересчитается.',
    'Add discounts only after hotel and rooms registration.' => 'Добавление скидок возможно только после регистрации отеля и номеров.',
    'Discounts addition is forbidden' => 'Добавление скидок невозможно',
    '{n, plural, one{# adult} other{# adults}}' => '{n, plural, one{# взрослый} other{# взрослых}}',
    '{n, plural, =0{} one{, # child (0 - 6 y.o.)} other{, # children (0 - 6 y.o.)}}' => '{n, plural, =0{} one{, # ребенок (0 - 6 лет)} few{, # ребенка (0 - 6 лет)} many{, # детей (0 - 6 лет)} other{, # ребенка (0 - 6 лет)}}',
    '{n, plural, =0{} one{, # child (7 - 11 y.o.)} other{, # children (7 - 11 y.o.)}}' => '{n, plural, =0{} one{, # ребенок (7 - 11 лет)} few{, # ребенка (7 - 11 лет)} many{, # детей (7 - 11 лет)} other{, # ребенка (7 - 11 лет)}}',
    'Price per day' => 'Стоимость проживания в день',
];
