<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'All messages' => 'Все сообщения',
    'Author' => 'Автор',
    'Cancel' => 'Отмена',
    'Created At' => 'Дата создания',
    'Created at' => 'Дата создания',
    'ID' => '',
    'Message text' => 'Текст сообщения',
    'New message to support' => 'Новое сообщение в службу поддержки',
    'New messages' => 'Новые сообщения',
    'Parent ID' => '',
    'Send' => 'Отправить',
    'Send new message' => 'Отправить новое сообщения',
    'Set as readed' => 'Отметить как прочитанное',
    'Support' => 'Поддержка',
    'Support message' => 'Сообщение в поддержку',
    'Support message #{n}' => 'Сообщение в поддержку №{n}',
    'Support team' => 'Служба поддержки',
    'Text' => 'Текст',
    'Total messages' => 'Всего сообщений',
    'Unread' => 'Не прочитано',
    'Unread admin' => '',
    'Unread messages: {n}' => 'Не прочитанных сообщений: {n}',
    'Updated At' => 'Дата обновления',
    'Updated at' => 'Дата обновления',
    'User message' => 'Сообщение пользователя',
    'Your message' => 'Ваше сообщение',
    'd/m/Y H:i:s' => 'd.m.Y H:i:s',
];
